/*
 * Executable handler for Dangerous Dave.
 *
 * Copyright (C) 2010-2021 Adam Nielsen <malvineous@shikadi.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

const FORMAT_ID = 'exe-ddave';

import Debug from '../util/debug.js';
const debug = Debug.extend(FORMAT_ID);

import CodeHandler_Simple from '../interface/CodeHandler_Simple.js';

export default class Code_DDave extends CodeHandler_Simple
{
	static metadata() {
		let md = {
			...super.metadata(),
			id: FORMAT_ID,
			title: 'Dangerous Dave',
		};

		return md;
	}

	static identify(content) {
		return this.identifyBySignature(
			content,
			0x1600,
			[0x4F, 0x01, 0x75, 0x1F]
		);
	}

	static attributes() {
		return [
			{ id: 'sfx.highscores.show',  type: 'uint16le', offset: 0x8A9, desc: 'Sound effect when high scores window appears.' },
			{ id: 'sfx.highscores.entry', type: 'uint16le', offset: 0x904, desc: 'Sound effect played five times, once for each high score entry.' },
			{ id: 'sfx.collect.gun',      type: 'uint16le', offset: 0x41A3, desc: 'Sound effect for collecting the gun.' },
			{ id: 'sfx.extralife',        type: 'uint16le', offset: 0xCE0, desc: 'Sound effect for getting an extra life.' },
			{ id: 'ui.label.jetpack',     type: 'uint16le', offset: 0x41C4, desc: 'Vertical coordinate of "Jetpack" (clipped to status area).' },
			{ id: 'game.endlevel.walkspeed', type: 'uint8', offset: 0x3D82, desc: 'How quickly the player walks across the screen in the end level cutscene.' },
			{ id: 'game.endlevel.walkend', type: 'uint16le', offset: 0x3D87, desc: 'How far the player must walk across the screen in the end level cutscene.  Lower numbers end the scene earlier without having made it all the way across the screen.' },
			{ id: 'game.endlevel.walk.sndtimer1', type: 'uint16le', offset: 0x3D6B, desc: 'Divisor for the timer that controls how fast the walk sound is played in the end level cutscene.' },
			{ id: 'game.endlevel.walk.sndtimer2', type: 'uint8', offset: 0x3D72, desc: 'Comparison for the timer that controls how fast the walk sound is played in the end level cutscene.' },
			{ id: 'game.initial.lives',   type: 'uint16le', offset: 0x537F, desc: 'Number of lives the player starts the game with.' },
			{ id: 'game.initial.scoreL',  type: 'uint16le', offset: 0x5385, desc: 'Initial score when starting a new game (low 16 bits).' },
			{ id: 'game.initial.scoreH',  type: 'uint16le', offset: 0x538B, desc: 'Initial score when starting a new game (high 16 bits).' },
			{ id: 'game.initial.level',   type: 'uint16le', offset: 0x53A3, desc: 'Starting level, 0 is first level.' },
			{ id: 'scancode.f12',         type: 'uint8', offset: 0x5724, desc: 'Should be 0x58 to work properly but the game ships with 0x59, making it impossible to assign F12 to an action.' },

			{ id: 'filename.scores', type: 'stringz', len: 12, offset: 0x2577E, desc: 'Filename to save high scores to.' },

			{ id: 'map.state.1',   type: 'uint8', offset: 0x257E8, desc: 'Initial player state bitflags for level 1.' },
			{ id: 'map.state.2',   type: 'uint8', desc: 'Initial player state bitflags for level 2.' },
			{ id: 'map.state.3',   type: 'uint8', desc: 'Initial player state bitflags for level 3.' },
			{ id: 'map.state.4',   type: 'uint8', desc: 'Initial player state bitflags for level 4.' },
			{ id: 'map.state.5',   type: 'uint8', desc: 'Initial player state bitflags for level 5.' },
			{ id: 'map.state.6',   type: 'uint8', desc: 'Initial player state bitflags for level 6.' },
			{ id: 'map.state.7',   type: 'uint8', desc: 'Initial player state bitflags for level 7.' },
			{ id: 'map.state.8',   type: 'uint8', desc: 'Initial player state bitflags for level 8.' },
			{ id: 'map.state.9',   type: 'uint8', desc: 'Initial player state bitflags for level 9.' },
			{ id: 'map.state.10',  type: 'uint8', desc: 'Initial player state bitflags for level 10.' },
			{ id: 'map.startX.1',  type: 'uint16le', desc: 'Initial player X-coordinate for level 1, in pixels.' },
			{ id: 'map.startX.2',  type: 'uint16le', desc: 'Initial player X-coordinate for level 2, in pixels.' },
			{ id: 'map.startX.3',  type: 'uint16le', desc: 'Initial player X-coordinate for level 3, in pixels.' },
			{ id: 'map.startX.4',  type: 'uint16le', desc: 'Initial player X-coordinate for level 4, in pixels.' },
			{ id: 'map.startX.5',  type: 'uint16le', desc: 'Initial player X-coordinate for level 5, in pixels.' },
			{ id: 'map.startX.6',  type: 'uint16le', desc: 'Initial player X-coordinate for level 6, in pixels.' },
			{ id: 'map.startX.7',  type: 'uint16le', desc: 'Initial player X-coordinate for level 7, in pixels.' },
			{ id: 'map.startX.8',  type: 'uint16le', desc: 'Initial player X-coordinate for level 8, in pixels.' },
			{ id: 'map.startX.9',  type: 'uint16le', desc: 'Initial player X-coordinate for level 9, in pixels.' },
			{ id: 'map.startX.10', type: 'uint16le', desc: 'Initial player X-coordinate for level 10, in pixels.' },
			{ id: 'map.startY.1',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 1, in pixels.' },
			{ id: 'map.startY.2',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 2, in pixels.' },
			{ id: 'map.startY.3',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 3, in pixels.' },
			{ id: 'map.startY.4',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 4, in pixels.' },
			{ id: 'map.startY.5',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 5, in pixels.' },
			{ id: 'map.startY.6',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 6, in pixels.' },
			{ id: 'map.startY.7',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 7, in pixels.' },
			{ id: 'map.startY.8',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 8, in pixels.' },
			{ id: 'map.startY.9',  type: 'uint16le', desc: 'Initial player Y-coordinate for level 9, in pixels.' },
			{ id: 'map.startY.10', type: 'uint16le', desc: 'Initial player Y-coordinate for level 10, in pixels.' },

			{ id: 'map.startY.warp',     type: 'uint16le', offset: 0x1710, desc: 'Initial player Y-coordinate for ALL warp zones, in pixels.' },
			{ id: 'map.state.warp',      type: 'uint16le', offset: 0x1716, desc: 'Initial player state bitflags for ALL warp zones.' },
			{ id: 'map.scrollX.1.warp',  type: 'uint16le', offset: 0x25862, desc: 'Initial horizontal scroll point for warp zone 1, in pixels.' },
			{ id: 'map.scrollX.2.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 2, in pixels.' },
			{ id: 'map.scrollX.3.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 3, in pixels.' },
			{ id: 'map.scrollX.4.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 4, in pixels.' },
			{ id: 'map.scrollX.5.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 5, in pixels.' },
			{ id: 'map.scrollX.6.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 6, in pixels.' },
			{ id: 'map.scrollX.7.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 7, in pixels.' },
			{ id: 'map.scrollX.8.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 8, in pixels.' },
			{ id: 'map.scrollX.9.warp',  type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 9, in pixels.' },
			{ id: 'map.scrollX.10.warp', type: 'uint16le', desc: 'Initial horizontal scroll point for warp zone 10, in pixels.' },
			{ id: 'map.startX.1.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 1, in pixels.' },
			{ id: 'map.startX.2.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 2, in pixels.' },
			{ id: 'map.startX.3.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 3, in pixels.' },
			{ id: 'map.startX.4.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 4, in pixels.' },
			{ id: 'map.startX.5.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 5, in pixels.' },
			{ id: 'map.startX.6.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 6, in pixels.' },
			{ id: 'map.startX.7.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 7, in pixels.' },
			{ id: 'map.startX.8.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 8, in pixels.' },
			{ id: 'map.startX.9.warp',   type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 9, in pixels.' },
			{ id: 'map.startX.10.warp',  type: 'uint16le', desc: 'Initial player X-coordinate for warp zone 10, in pixels.' },

			{ id: 'item.1.tile',   type: 'uint16le', offset: 0x2590A, desc: 'Tile number of item 1 in map tileset.' },
			{ id: 'item.2.tile',   type: 'uint16le', desc: 'Tile number of item 2 in map tileset.' },
			{ id: 'item.3.tile',   type: 'uint16le', desc: 'Tile number of item 3 in map tileset.' },
			{ id: 'item.4.tile',   type: 'uint16le', desc: 'Tile number of item 4 in map tileset.' },
			{ id: 'item.5.tile',   type: 'uint16le', desc: 'Tile number of item 5 in map tileset.' },
			{ id: 'item.6.tile',   type: 'uint16le', desc: 'Tile number of item 6 in map tileset.' },
			{ id: 'item.7.tile',   type: 'uint16le', desc: 'Tile number of item 7 in map tileset.' },
			{ id: 'item.8.tile',   type: 'uint16le', desc: 'Tile number of item 8 in map tileset.' },
			{ id: 'item.9.tile',   type: 'uint16le', desc: 'Tile number of item 9 in map tileset.' },
			{ id: 'item.10.tile',  type: 'uint16le', desc: 'Tile number of item 10 in map tileset.' },
			{ id: 'item.1.points', type: 'uint16le', desc: 'Points awarded by item 1.' },
			{ id: 'item.2.points', type: 'uint16le', desc: 'Points awarded by item 2.' },
			{ id: 'item.3.points',  type: 'uint16le', desc: 'Points awarded by item 3.' },
			{ id: 'item.4.points',  type: 'uint16le', desc: 'Points awarded by item 4.' },
			{ id: 'item.5.points',  type: 'uint16le', desc: 'Points awarded by item 5.' },
			{ id: 'item.6.points',  type: 'uint16le', desc: 'Points awarded by item 6.' },
			{ id: 'item.7.points',  type: 'uint16le', desc: 'Points awarded by item 7.' },
			{ id: 'item.8.points',  type: 'uint16le', desc: 'Points awarded by item 8.' },
			{ id: 'item.9.points',  type: 'uint16le', desc: 'Points awarded by item 9.' },
			{ id: 'item.10.points', type: 'uint16le', desc: 'Points awarded by item 10.' },

			{ id: 'ui.header.score',   type: 'stringz', len: 6, offset: 0x25E9E },
			// Skip level shown on title screen (arc-exe-ddave handles that)
			{ id: 'msg.level.end.1',   type: 'stringz', len: 35, offset: 0x25EEA },
			{ id: 'msg.level.end.9',   type: 'stringz', len: 35 },
			{ id: 'msg.level.end.10',  type: 'stringz', len: 35 },

			{ id: 'default.hsc.1.level',    type: 'uint8' },
			{ id: 'default.hsc.1.digit.1',  type: 'uint8' },
			{ id: 'default.hsc.1.digit.2',  type: 'uint8' },
			{ id: 'default.hsc.1.digit.3',  type: 'uint8' },
			{ id: 'default.hsc.1.digit.4',  type: 'uint8' },
			{ id: 'default.hsc.1.digit.5',  type: 'uint8' },
			{ id: 'default.hsc.1.name',     type: 'string', len: 3 },

			{ id: 'default.hsc.2.level',    type: 'uint8' },
			{ id: 'default.hsc.2.digit.1',  type: 'uint8' },
			{ id: 'default.hsc.2.digit.2',  type: 'uint8' },
			{ id: 'default.hsc.2.digit.3',  type: 'uint8' },
			{ id: 'default.hsc.2.digit.4',  type: 'uint8' },
			{ id: 'default.hsc.2.digit.5',  type: 'uint8' },
			{ id: 'default.hsc.2.name',     type: 'string', len: 3 },

			{ id: 'default.hsc.3.level',    type: 'uint8' },
			{ id: 'default.hsc.3.digit.1',  type: 'uint8' },
			{ id: 'default.hsc.3.digit.2',  type: 'uint8' },
			{ id: 'default.hsc.3.digit.3',  type: 'uint8' },
			{ id: 'default.hsc.3.digit.4',  type: 'uint8' },
			{ id: 'default.hsc.3.digit.5',  type: 'uint8' },

			{ id: 'default.hsc.4.name',     type: 'string', len: 3 },
			{ id: 'default.hsc.4.level',    type: 'uint8' },
			{ id: 'default.hsc.4.digit.1',  type: 'uint8' },
			{ id: 'default.hsc.4.digit.2',  type: 'uint8' },
			{ id: 'default.hsc.4.digit.3',  type: 'uint8' },
			{ id: 'default.hsc.4.digit.4',  type: 'uint8' },
			{ id: 'default.hsc.4.digit.5',  type: 'uint8' },
			{ id: 'default.hsc.4.name',     type: 'string', len: 3 },

			{ id: 'default.hsc.5.level',    type: 'uint8' },
			{ id: 'default.hsc.5.digit.1',  type: 'uint8' },
			{ id: 'default.hsc.5.digit.2',  type: 'uint8' },
			{ id: 'default.hsc.5.digit.3',  type: 'uint8' },
			{ id: 'default.hsc.5.digit.4',  type: 'uint8' },
			{ id: 'default.hsc.5.digit.5',  type: 'uint8' },
			{ id: 'default.hsc.5.name',     type: 'string', len: 3 },

			{ id: 'msg.hsc',           type: 'stringz', len: 22 },
			{ id: 'msg.gameover',      type: 'stringz', len: 10 },
			{ id: 'msg.hsc.header',    type: 'stringz', len: 55 },
			{ id: 'msg.hsc.entry.eol', type: 'stringz', len: 4, desc: 'Printed after each high score entry to go to the next line ready for the next entry.' },
			{ id: 'msg.restart',       type: 'stringz', len: 24 },

			{ id: 'msg.help.1.1',      type: 'stringz', len: 26 },
			{ id: 'msg.help.1.2',      type: 'stringz', len: 24 },
			{ id: 'msg.help.1.3',      type: 'stringz', len: 25 },
			{ id: 'msg.help.1.4',      type: 'stringz', len: 20 },
			{ id: 'msg.help.1.5',      type: 'stringz', len: 25 },
			{ id: 'msg.help.1.6',      type: 'stringz', len: 26 },
			{ id: 'msg.help.1.7',      type: 'stringz', len: 16 },
			{ id: 'msg.help.1.8',      type: 'stringz', len: 12 },
			{ id: 'msg.help.1.9',      type: 'stringz', len: 21 },
			{ id: 'msg.help.1.10',     type: 'stringz', len: 20 },
			{ id: 'msg.help.1.11',     type: 'stringz', len: 18 },
			{ id: 'msg.help.1.12',     type: 'stringz', len: 26 },
			{ id: 'msg.help.1.13',     type: 'stringz', len: 22 },
			{ id: 'msg.help.2.1',      type: 'stringz', len: 25 },
			{ id: 'msg.help.2.2',      type: 'stringz', len: 28 },
			{ id: 'msg.help.2.3',      type: 'stringz', len: 27 },
			{ id: 'msg.help.2.4',      type: 'stringz', len: 28 },
			{ id: 'msg.help.2.5',      type: 'stringz', len: 28 },
			{ id: 'msg.help.2.6',      type: 'stringz', len: 24 },
			{ id: 'msg.help.2.7',      type: 'stringz', len: 29 },
			{ id: 'msg.help.2.8',      type: 'stringz', len: 29 },
			{ id: 'msg.help.2.9',      type: 'stringz', len: 29 },
			{ id: 'msg.help.2.10',     type: 'stringz', len: 27 },
			{ id: 'msg.help.2.11',     type: 'stringz', len: 29 },
			{ id: 'msg.help.2.12',     type: 'stringz', len: 29 },
			{ id: 'msg.help.2.13',     type: 'stringz', len: 29 },
			{ id: 'msg.help.2.14',     type: 'stringz', len: 18 },
			{ id: 'msg.help.2.15',     type: 'stringz', len: 22 },
			{ id: 'msg.help.3.1',      type: 'stringz', len: 25 },
			{ id: 'msg.help.3.2',      type: 'stringz', len: 28 },
			{ id: 'msg.help.3.3',      type: 'stringz', len: 29 },
			{ id: 'msg.help.3.4',      type: 'stringz', len: 28 },
			{ id: 'msg.help.3.5',      type: 'stringz', len: 29 },
			{ id: 'msg.help.3.6',      type: 'stringz', len: 30 },
			{ id: 'msg.help.3.7',      type: 'stringz', len: 30 },
			{ id: 'msg.help.3.8',      type: 'stringz', len: 27 },
			{ id: 'msg.help.3.9',      type: 'stringz', len: 15 },
			{ id: 'msg.help.3.10',     type: 'stringz', len: 27 },
			{ id: 'msg.help.3.11',     type: 'stringz', len: 29 },
			{ id: 'msg.help.3.12',     type: 'stringz', len: 28 },
			{ id: 'msg.help.3.13',     type: 'stringz', len: 17 },
			{ id: 'msg.help.3.14',     type: 'stringz', len: 20 },
			{ id: 'msg.quit',          type: 'stringz', len: 16 },
			{ id: 'msg.pause',         type: 'stringz', len: 23 },
			{ id: 'filename.gfx.ega',  type: 'stringz', len: 12 },
			{ id: 'msg.title.1',       type: 'stringz', len: 22 },
			{ id: 'msg.title.2',       type: 'stringz', len: 27 },
			{ id: 'msg.title.3',       type: 'stringz', len: 26 },
			{ id: 'msg.end.1',         type: 'stringz', len: 30 },
			{ id: 'msg.end.2',         type: 'stringz', len: 37 },
			{ id: 'msg.end.3',         type: 'stringz', len: 33 },
			{ id: 'msg.end.4',         type: 'stringz', len: 31 },
			{ id: 'msg.end.5',         type: 'stringz', len: 37 },
			{ id: 'msg.end.6',         type: 'stringz', len: 36 },
			{ id: 'msg.end.7',         type: 'stringz', len: 35 },
			{ id: 'msg.end.8',         type: 'stringz', len: 36 },
			{ id: 'msg.end.9',         type: 'stringz', len: 35 },
			{ id: 'msg.end.10',        type: 'stringz', len: 23 },

			{ id: 'cp.row.video',      type: 'uint16le', len: 2, desc: 'Control Panel: Which row the video device selection appears on.' },
			{ id: 'cp.row.sound',      type: 'uint16le', len: 2, desc: 'Control Panel: Which row the sound device selection appears on.' },
			{ id: 'cp.row.input',      type: 'uint16le', len: 2, desc: 'Control Panel: Which row the input device selection appears on.' },
			{ id: 'cp.row.unknown',    type: 'uint16le', len: 2, desc: 'Control Panel: Unknown effect.' },
			{ id: 'cp.col.1',          type: 'uint16le', len: 2, desc: 'Control Panel: Position of first column of devices.' },
			{ id: 'cp.col.2',          type: 'uint16le', len: 2, desc: 'Control Panel: Position of second column of devices.' },
			{ id: 'cp.col.3',          type: 'uint16le', len: 2, desc: 'Control Panel: Position of third column of devices.' },
			{ id: 'cp.col.4',          type: 'uint16le', len: 2, desc: 'Control Panel: Position of fourth column of devices.' },
			{ id: 'cp.keynames',       type: 'stringz', len: 93, desc: 'Key names shown when selecting keyboard buttons.' },
			{ id: 'cp.msg.joy.1',      type: 'stringz', len: 26 },
			{ id: 'cp.msg.joy.2',      type: 'stringz', len: 26 },
			{ id: 'cp.msg.joy.3',      type: 'stringz', len: 27 },
			{ id: 'cp.msg.joy.4',      type: 'stringz', len: 13 },
			{ id: 'cp.msg.joy.5',      type: 'stringz', len: 21 },
			{ id: 'cp.msg.joy.6',      type: 'stringz', len: 30 },
			{ id: 'cp.msg.joy.7',      type: 'stringz', len: 14 },
			{ id: 'cp.msg.joy.8',      type: 'stringz', len: 21 },
			{ id: 'cp.msg.mouse.1',    type: 'stringz', len: 27 },
			{ id: 'cp.msg.mouse.2',    type: 'stringz', len: 27 },
			{ id: 'cp.msg.mouse.3',    type: 'stringz', len: 27 },
			{ id: 'cp.msg.mouse.4',    type: 'stringz', len: 27 },
			{ id: 'cp.msg.mouse.5',    type: 'stringz', len: 20 },
			{ id: 'cp.keyname.esc',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.bksp',   type: 'stringz', len: 5 },
			{ id: 'cp.keyname.tab',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.ctrl',   type: 'stringz', len: 5 },
			{ id: 'cp.keyname.lshift', type: 'stringz', len: 7 },
			{ id: 'cp.keyname.space',  type: 'stringz', len: 6 },
			{ id: 'cp.keyname.caps',   type: 'stringz', len: 7 },
			{ id: 'cp.keyname.fx',     type: 'stringz', len: 2 },
			{ id: 'cp.keyname.f11',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.f12',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.scroll', type: 'stringz', len: 7 },
			{ id: 'cp.keyname.enter',  type: 'stringz', len: 6 },
			{ id: 'cp.keyname.rshift', type: 'stringz', len: 7 },
			{ id: 'cp.keyname.prtsc',  type: 'stringz', len: 6 },
			{ id: 'cp.keyname.alt',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.home',   type: 'stringz', len: 5 },
			{ id: 'cp.keyname.pgup',   type: 'stringz', len: 5 },
			{ id: 'cp.keyname.end',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.pgdn',   type: 'stringz', len: 5 },
			{ id: 'cp.keyname.ins',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.del',    type: 'stringz', len: 4 },
			{ id: 'cp.keyname.num',    type: 'stringz', len: 6 },
			{ id: 'cp.msg.keyb.1',     type: 'stringz', len: 25 },
			{ id: 'cp.msg.keyb.2',     type: 'stringz', len: 23 },
			{ id: 'cp.msg.keyb.3',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.4',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.5',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.6',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.7',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.8',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.9',     type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.10',    type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.11',    type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.12',    type: 'stringz', len: 15 },
			{ id: 'cp.msg.keyb.13',    type: 'stringz', len: 24 },
			{ id: 'cp.msg.keyb.14',    type: 'stringz', len: 21 },
			{ id: 'cp.msg.keyb.15',    type: 'stringz', len: 20, desc: 'Set after a key is chosen, erases the "Press the new key" message.' },
			{ id: 'cp.msg.keyb.16',    type: 'stringz', len: 9, desc: 'Printed after key name to erase any previous key name that was longer than the new key name.' },
			{ id: 'cp.main.title',     type: 'stringz', len: 26 },
			{ id: 'cp.main.video',     type: 'stringz', len: 7 },
			{ id: 'cp.main.sound',     type: 'stringz', len: 7 },
			{ id: 'cp.main.input',     type: 'stringz', len: 9 },
			{ id: 'cp.main.footer.1',  type: 'stringz', len: 41 },
			{ id: 'cp.main.footer.2',  type: 'stringz', len: 41 },
			{ id: 'cp.main.footer.3',  type: 'stringz', len: 42 },

		];
	}
}
